### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by athina1**

### CODE REVIEW

**Comment by marcopasi** [comment]
Hi Athina,
Thanks for the addition. Several (all?) modules in the package refer to a "NOTICE" file: do we need to add one of those as well?

**Comment by markmcdowall** [comment]
The NOTICE file is where you record the relevant Copyright information about your institute, int this case Uni of Notts.

I'll then add a line for the EMBL-EBI.

See https://github.com/Multiscale-Genomics/mg-process-fastq/blob/master/NOTICE as an example

There are 2 entries, one for the copyright covering the years that you have made changes or actively work on the code or maintain, the second is a complete list of all those that have contributed. To all intents and purposes both lists will have the same institutes lists.

**Comment by athina1** [comment]
Hi both, I just created the NOTICE file - I wasn't too sure about the dates so I just put 2015-2018, let me know if that's ok?

**Comment by marcopasi** [comment]
Hi Mark, hi Athina,
I've had a look at NOTICE and it seems to me it is still not complete. Could you confirm whether this can be merged or not?
Cheers,
Marco

**Comment by athina1** [comment]
Hi Marco,

Any changes I’ve made are in the add-license-1 branch which hasn’t been merged yet as I wasn’t sure if I was meant to merge it or not. What do you believe that the NOTICE file is missing?

Athina

**Comment by markmcdowall** [comment]
Can this branch get merged?

The NOTICE file in the add-license-1 branch looks complete. Once merged I'll add and entry for the EBI as well.

Cheers,

Mark

**Comment by athina1** [comment]
Hi Mark,

I'm happy to do a merge pull request, I just didn't know what the protocol was about merging.

Kind regards,
Athina

**Comment by markmcdowall** [comment]
You should be good to go for pressing the "Merge pull request" button.

There should be no real conflicts in the code.

It might be worth setting up Travis to run unit tests and enforce style guides on the code. We can do this as a separate branch after. Happy to get this started though.

Cheers,

Mark

**Comment by athina1** [comment]
Oops I merged it just before I read your message but yes I think it should be fine as all that's changed is a couple lines in the headers.

Yes please if you can get Travis set up that would be great - if I get this correctly this is for other branches where more extensive changes to the code have been made so that we make sure nothing has gone wrong? But I mean we didn't really need it for this one did we?

Thanks!

Athina

**Comment by markmcdowall** [comment]
Correct. I have started the Travis work as a new branch.

As for the unit tests that need to be performed that might take a bit longer to add in, but can be done as we go along

**Pull request merged**
